project_name: dateparse
builds:
  -
    id: "dateparse"
    binary: "dateparse"
    dir: dateparse
  -
    id: "example"
    binary: "example"
    dir: example
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native
  sort: asc
  filters:
    include:
      - "^feat:"
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: dateparse
    homepage: https://github.com/oarkflow/date
    maintainer: IT Lightning, LLC <opensource@itlightning.com>
    description: NA
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
